import { ReactNode } from 'react';
import DataTable, { ColumnDef, FilterConfig } from '../DataTable';
import { formatMsrp, formatDimensions, formatPower } from '../../utils/formatters';

interface Pedal {
  id: number;
  manufacturer: string;
  model: string;
  effect_type: string | null;
  in_production: boolean;
  width_mm: number | null;
  depth_mm: number | null;
  height_mm: number | null;
  weight_grams: number | null;
  msrp_cents: number | null;
  product_page: string | null;
  instruction_manual: string | null;
  image_path: string | null;
  color_options: string | null;
  data_reliability: 'High' | 'Medium' | 'Low' | null;
  bypass_type: string | null;
  signal_type: string | null;
  circuit_type: string | null;
  mono_stereo: string | null;
  preset_count: number;
  midi_capable: boolean;
  has_tap_tempo: boolean;
  battery_capable: boolean;
  has_software_editor: boolean;
  power_voltage: string | null;
  power_current_ma: number | null;
}

// TODO: Replace with API call to SQLite backend
const DATA: Pedal[] = [{"id":68,"manufacturer":"1981 Inventions","model":"DRV","effect_type":"Gain","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":25000,"product_page":"https://1981inventions.com/items/drv","instruction_manual":null,"image_path":null,"color_options":"White No3, Black No3, Gold No3, Black/Pink No3, Hyperfade White, Hyperfade Black, Silver, Vaporwave, Silver (Professional)","data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":69,"manufacturer":"1981 Inventions","model":"LVL","effect_type":"Gain","in_production":true,"width_mm":62.0,"depth_mm":112.0,"height_mm":36.0,"weight_grams":null,"msrp_cents":22900,"product_page":"https://1981inventions.com/items/levelisimportant","instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":45},
{"id":70,"manufacturer":"1981 Inventions","model":"MMHMM 20th Anniversary","effect_type":"Gain","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":25000,"product_page":"https://1981inventions.com/products/mmhmm-20th-anniversary","instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V/18V DC","power_current_ma":null},
{"id":71,"manufacturer":"3 Leaf Audio","model":"Doom 2","effect_type":"Fuzz","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":33300,"product_page":"https://www.3leafaudio.com/shop/doom-775fk","instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":7},
{"id":73,"manufacturer":"3 Leaf Audio","model":"Octabvre MK3.33","effect_type":"Other","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":33300,"product_page":"https://www.3leafaudio.com/shop/octabvre","instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":30},
{"id":72,"manufacturer":"3 Leaf Audio","model":"Proton MK4","effect_type":"Other","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":33300,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9-18V DC","power_current_ma":null},
{"id":83,"manufacturer":"ADA Amps","model":"APP-1","effect_type":"Preamp","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":49995,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":87,"manufacturer":"ADA Amps","model":"Definition","effect_type":"Utility","in_production":false,"width_mm":114.3,"depth_mm":63.5,"height_mm":38.1,"weight_grams":null,"msrp_cents":19995,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9-18V DC","power_current_ma":null},
{"id":82,"manufacturer":"ADA Amps","model":"Final Phase Reissue","effect_type":"Other","in_production":false,"width_mm":171.5,"depth_mm":146.1,"height_mm":76.2,"weight_grams":null,"msrp_cents":24900,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"120V AC","power_current_ma":null},
{"id":81,"manufacturer":"ADA Amps","model":"Flanger Reissue","effect_type":"Other","in_production":false,"width_mm":171.5,"depth_mm":146.1,"height_mm":76.2,"weight_grams":null,"msrp_cents":57500,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"18V DC","power_current_ma":null},
{"id":84,"manufacturer":"ADA Amps","model":"GCS-2","effect_type":"Amp/Cab Sim","in_production":true,"width_mm":85.1,"depth_mm":106.7,"height_mm":45.7,"weight_grams":null,"msrp_cents":null,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":85,"manufacturer":"ADA Amps","model":"GCS-3","effect_type":"Amp/Cab Sim","in_production":true,"width_mm":85.1,"depth_mm":106.7,"height_mm":45.7,"weight_grams":null,"msrp_cents":null,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":200},
{"id":86,"manufacturer":"ADA Amps","model":"MP-1 Channel","effect_type":"Preamp","in_production":true,"width_mm":137.2,"depth_mm":127.0,"height_mm":45.7,"weight_grams":null,"msrp_cents":39995,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"12V DC","power_current_ma":800},
{"id":75,"manufacturer":"Abasi","model":"Micro-Aggressor","effect_type":"Compression","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":24999,"product_page":"https://abasiconcepts.com/products/micro-aggressor","instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":74,"manufacturer":"Abasi","model":"Pathos","effect_type":"Gain","in_production":true,"width_mm":63.5,"depth_mm":114.3,"height_mm":38.1,"weight_grams":null,"msrp_cents":18500,"product_page":"https://abasiconcepts.com/products/pathos","instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":30},
{"id":79,"manufacturer":"Aclam","model":"Cinnamon Drive","effect_type":"Gain","in_production":true,"width_mm":137.2,"depth_mm":86.4,"height_mm":55.9,"weight_grams":null,"msrp_cents":29900,"product_page":"https://www.aclamguitars.com/store/cinnamon-drive.html","instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":35},
{"id":76,"manufacturer":"Aclam","model":"Dr. Robert V3","effect_type":"Gain","in_production":false,"width_mm":137.2,"depth_mm":86.4,"height_mm":55.9,"weight_grams":null,"msrp_cents":32900,"product_page":"https://www.aclamguitars.com/store/dr-robert-v3.html","instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":100},
{"id":80,"manufacturer":"Aclam","model":"The Mocker","effect_type":"Fuzz","in_production":false,"width_mm":137.2,"depth_mm":86.4,"height_mm":55.9,"weight_grams":null,"msrp_cents":29900,"product_page":"https://www.aclamguitars.com/store/the-mocker.html","instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":12},
{"id":78,"manufacturer":"Aclam","model":"The Windmiller Preamp","effect_type":"Preamp","in_production":true,"width_mm":137.2,"depth_mm":86.4,"height_mm":55.9,"weight_grams":null,"msrp_cents":31900,"product_page":"https://www.aclamguitars.com/store/the-windmiller.html","instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":38},
{"id":77,"manufacturer":"Aclam","model":"The Woman Tone","effect_type":"Gain","in_production":true,"width_mm":137.2,"depth_mm":86.4,"height_mm":55.9,"weight_grams":null,"msrp_cents":33900,"product_page":"https://www.aclamguitars.com/store/the-woman-tone.html","instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":40},
{"id":88,"manufacturer":"Adventure Audio","model":"Dream Reaper","effect_type":"Fuzz","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":92,"manufacturer":"Adventure Audio","model":"Glacial Zenith","effect_type":"Gain","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":16900,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":93,"manufacturer":"Adventure Audio","model":"Juniper","effect_type":"Gain","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Low","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":89,"manufacturer":"Adventure Audio","model":"Outer Rings","effect_type":"Other","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":24900,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":90,"manufacturer":"Adventure Audio","model":"Power Couple","effect_type":"Utility","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":50},
{"id":91,"manufacturer":"Adventure Audio","model":"Whateverb V2","effect_type":"Reverb","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":250},
{"id":94,"manufacturer":"Aguilar","model":"Agro Bass Overdrive","effect_type":"Gain","in_production":true,"width_mm":57.2,"depth_mm":63.5,"height_mm":120.7,"weight_grams":null,"msrp_cents":22900,"product_page":"https://aguilaramp.com/products/agro-bass-overdrive-pedal","instruction_manual":"https://aguilar.korg-kid.com/manual/AGRO","image_path":null,"color_options":null,"data_reliability":"Low","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":null,"power_current_ma":null},
{"id":97,"manufacturer":"Aguilar","model":"Chorusaurus Bass Chorus","effect_type":"Other","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":22900,"product_page":"https://aguilaramp.com/en-int/products/chorusaurus-bass-chorus-pedal","instruction_manual":"https://aguilar.korg-kid.com/manual/CHORUSAURUS","image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":null,"power_current_ma":null},
{"id":98,"manufacturer":"Aguilar","model":"Chorusaurus Bass Chorus V2","effect_type":"Other","in_production":true,"width_mm":57.2,"depth_mm":63.5,"height_mm":120.7,"weight_grams":null,"msrp_cents":24900,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":null,"power_current_ma":null},
{"id":104,"manufacturer":"Aguilar","model":"Filter Twin Dual Bass Envelope Filter","effect_type":"Other","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":24900,"product_page":null,"instruction_manual":"https://aguilar.korg-kid.com/manual/FILTER_TWIN","image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":null,"power_current_ma":null},
{"id":95,"manufacturer":"Aguilar","model":"Fuzzistor Bass Fuzz","effect_type":"Fuzz","in_production":true,"width_mm":57.2,"depth_mm":63.5,"height_mm":120.7,"weight_grams":null,"msrp_cents":17900,"product_page":"https://aguilaramp.com/products/fuzzistor-bass-fuzz-pedal","instruction_manual":"https://aguilar.korg-kid.com/manual/FUZZISTOR","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":null,"power_current_ma":null},
{"id":96,"manufacturer":"Aguilar","model":"Fuzzistor Bass Fuzz V2","effect_type":"Fuzz","in_production":true,"width_mm":57.2,"depth_mm":63.5,"height_mm":120.7,"weight_grams":null,"msrp_cents":19900,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":null,"power_current_ma":null},
{"id":102,"manufacturer":"Aguilar","model":"Grape Phaser Bass Pedal","effect_type":"Other","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":19900,"product_page":null,"instruction_manual":"https://aguilar.korg-kid.com/manual/GRAPE_PHASER","image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":null,"power_current_ma":null},
{"id":99,"manufacturer":"Aguilar","model":"Octamizer Analog Bass Octave","effect_type":"Other","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":17900,"product_page":"https://aguilaramp.com/products/octamizer-analog-bass-octave-pedal","instruction_manual":"https://aguilar.korg-kid.com/manual/OCTAMIZER","image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":null,"power_current_ma":null},
{"id":100,"manufacturer":"Aguilar","model":"Octamizer V2 Analog Bass Octave","effect_type":"Other","in_production":true,"width_mm":57.2,"depth_mm":63.5,"height_mm":120.7,"weight_grams":null,"msrp_cents":19900,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":null,"power_current_ma":null},
{"id":101,"manufacturer":"Aguilar","model":"Storm King Distortion Bass Pedal","effect_type":"Fuzz","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":16900,"product_page":"https://aguilaramp.com/products/storm-king-distortion-bass-pedal","instruction_manual":"https://aguilar.korg-kid.com/manual/STORM_KING","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":null,"power_current_ma":null},
{"id":103,"manufacturer":"Aguilar","model":"TLC Bass Compressor","effect_type":"Compression","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":22900,"product_page":null,"instruction_manual":"https://aguilar.korg-kid.com/manual/TLC_COMP","image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":null,"power_current_ma":null},
{"id":45,"manufacturer":"JHS Pedals","model":"3 Series Distortion","effect_type":"Gain","in_production":true,"width_mm":112.3,"depth_mm":60.5,"height_mm":31.0,"weight_grams":null,"msrp_cents":9900,"product_page":"https://jhspedals.info/products/3-series-distortion","instruction_manual":"https://manuals.plus/jhs/pedals-3-series-distortion-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":70},
{"id":44,"manufacturer":"JHS Pedals","model":"3 Series Flanger","effect_type":"Other","in_production":true,"width_mm":112.3,"depth_mm":60.5,"height_mm":31.0,"weight_grams":null,"msrp_cents":9900,"product_page":"https://jhspedals.info/products/3-series-flanger","instruction_manual":"https://manuals.plus/jhs/pedals-3-series-flanger-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":70},
{"id":43,"manufacturer":"JHS Pedals","model":"3 Series Fuzz","effect_type":"Fuzz","in_production":true,"width_mm":112.3,"depth_mm":60.5,"height_mm":31.0,"weight_grams":null,"msrp_cents":9900,"product_page":"https://jhspedals.info/products/3-series-fuzz","instruction_manual":"https://manuals.plus/jhs/pedals-3-series-fuzz-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":70},
{"id":46,"manufacturer":"JHS Pedals","model":"3 Series Harmonic Tremolo","effect_type":"Other","in_production":true,"width_mm":112.3,"depth_mm":60.5,"height_mm":31.0,"weight_grams":null,"msrp_cents":9900,"product_page":"https://jhspedals.info/products/3-series-harmonic-tremolo","instruction_manual":"https://manuals.plus/jhs/pedals-3-series-harmonic-tremolo-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":70},
{"id":39,"manufacturer":"JHS Pedals","model":"3 Series Octave Reverb","effect_type":"Reverb","in_production":true,"width_mm":112.3,"depth_mm":60.5,"height_mm":31.0,"weight_grams":null,"msrp_cents":9900,"product_page":"https://jhspedals.info/products/3-series-octave-reverb","instruction_manual":"https://manuals.plus/jhs/pedals-3-series-octave-reverb-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":70},
{"id":36,"manufacturer":"JHS Pedals","model":"3 Series Oil Can Delay","effect_type":"Delay","in_production":true,"width_mm":112.3,"depth_mm":60.5,"height_mm":31.0,"weight_grams":null,"msrp_cents":9900,"product_page":"https://jhspedals.info/products/3-series-oil-can-delay","instruction_manual":"https://manuals.plus/jhs/pedals-3-series-oil-can-delay-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":70},
{"id":42,"manufacturer":"JHS Pedals","model":"3 Series Overdrive","effect_type":"Gain","in_production":true,"width_mm":112.3,"depth_mm":60.5,"height_mm":31.0,"weight_grams":null,"msrp_cents":9900,"product_page":"https://jhspedals.info/products/3-series-overdrive","instruction_manual":"https://manuals.plus/jhs/pedals-3-series-overdrive-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":70},
{"id":40,"manufacturer":"JHS Pedals","model":"3 Series Reverb","effect_type":"Reverb","in_production":true,"width_mm":112.3,"depth_mm":60.5,"height_mm":31.0,"weight_grams":null,"msrp_cents":9900,"product_page":"https://jhspedals.info/products/3-series-reverb","instruction_manual":"https://manuals.plus/jhs/pedals-3-series-reverb-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":70},
{"id":37,"manufacturer":"JHS Pedals","model":"3 Series Rotary Chorus","effect_type":"Other","in_production":true,"width_mm":112.3,"depth_mm":60.5,"height_mm":31.0,"weight_grams":null,"msrp_cents":9900,"product_page":"https://jhspedals.info/products/3-series-rotary-chorus","instruction_manual":"https://manuals.plus/jhs/pedals-3-series-rotary-chorus-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":70},
{"id":41,"manufacturer":"JHS Pedals","model":"3 Series Screamer","effect_type":"Gain","in_production":true,"width_mm":112.3,"depth_mm":60.5,"height_mm":31.0,"weight_grams":null,"msrp_cents":9900,"product_page":"https://jhspedals.info/products/3-series-screamer","instruction_manual":"https://manuals.plus/jhs/pedals-3-series-screamer-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":70},
{"id":38,"manufacturer":"JHS Pedals","model":"3 Series Tape Delay","effect_type":"Delay","in_production":true,"width_mm":112.3,"depth_mm":60.5,"height_mm":31.0,"weight_grams":null,"msrp_cents":9900,"product_page":"https://jhspedals.info/products/3-series-tape-delay","instruction_manual":"https://manuals.plus/jhs/pedals-3-series-tape-delay-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":70},
{"id":3,"manufacturer":"JHS Pedals","model":"424 Gain Stage","effect_type":"Gain","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":24900,"product_page":"https://jhspedals.info/products/424-gain-stage","instruction_manual":"https://manuals.plus/jhs/pedals-424-gain-stage-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":17,"manufacturer":"JHS Pedals","model":"AT+","effect_type":"Gain","in_production":true,"width_mm":55.9,"depth_mm":121.9,"height_mm":40.6,"weight_grams":null,"msrp_cents":21900,"product_page":"https://jhspedals.info/products/at","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":15},
{"id":29,"manufacturer":"JHS Pedals","model":"Active A/B/Y","effect_type":"Utility","in_production":false,"width_mm":112.3,"depth_mm":60.5,"height_mm":31.0,"weight_grams":null,"msrp_cents":13000,"product_page":"https://jhspedals.info/products/active-aby","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":47},
{"id":18,"manufacturer":"JHS Pedals","model":"Angry Charlie V3","effect_type":"Gain","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":19900,"product_page":"https://jhspedals.info/products/angry-charlie-v3","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":35,"manufacturer":"JHS Pedals","model":"Artificial Blonde","effect_type":"Gain","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":24900,"product_page":"https://jhspedals.info/products/artificial-blonde","instruction_manual":"https://manuals.plus/jhs/pedals-artificial-blonde-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":59,"manufacturer":"JHS Pedals","model":"Bat Sim","effect_type":"Utility","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":"https://jhspedals.info/products/bat-sim","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":55,"manufacturer":"JHS Pedals","model":"Big Muffuletta","effect_type":"Fuzz","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":"https://jhspedals.info/products/big-muffuletta","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":14,"manufacturer":"JHS Pedals","model":"Bonsai","effect_type":"Gain","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":24900,"product_page":"https://jhspedals.info/products/bonsai","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":20},
{"id":23,"manufacturer":"JHS Pedals","model":"Charlie Brown V4","effect_type":"Gain","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":19900,"product_page":"https://jhspedals.info/products/charlie-brown-v4","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":100},
{"id":27,"manufacturer":"JHS Pedals","model":"Cheese Ball","effect_type":"Fuzz","in_production":true,"width_mm":66.0,"depth_mm":121.9,"height_mm":40.6,"weight_grams":null,"msrp_cents":17900,"product_page":"https://jhspedals.info/products/cheese-ball","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":9},
{"id":24,"manufacturer":"JHS Pedals","model":"Clover","effect_type":"Preamp","in_production":true,"width_mm":66.0,"depth_mm":121.9,"height_mm":40.6,"weight_grams":null,"msrp_cents":19900,"product_page":"https://jhspedals.info/products/clover","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":7,"manufacturer":"JHS Pedals","model":"Colour Box 10","effect_type":"Preamp","in_production":true,"width_mm":144.8,"depth_mm":95.3,"height_mm":47.0,"weight_grams":null,"msrp_cents":44900,"product_page":"https://jhspedals.info/products/colour-box-10","instruction_manual":"https://manuals.plus/jhs/pedals-colour-box-10-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":193},
{"id":6,"manufacturer":"JHS Pedals","model":"Colour Box V2","effect_type":"Preamp","in_production":true,"width_mm":144.8,"depth_mm":95.3,"height_mm":47.0,"weight_grams":null,"msrp_cents":44900,"product_page":"https://jhspedals.info/products/colour-box-v2","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":193},
{"id":34,"manufacturer":"JHS Pedals","model":"Crayon","effect_type":"Gain","in_production":true,"width_mm":66.0,"depth_mm":121.9,"height_mm":40.6,"weight_grams":null,"msrp_cents":19900,"product_page":"https://jhspedals.info/products/crayon","instruction_manual":"https://manuals.plus/jhs/pedals-crayon-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":100},
{"id":50,"manufacturer":"JHS Pedals","model":"Double Barrel V4","effect_type":"Multi Effects","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":29900,"product_page":"https://jhspedals.info/products/double-barrel-v4","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":47,"manufacturer":"JHS Pedals","model":"EHX by JHS - Big Muff 2","effect_type":"Fuzz","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":24900,"product_page":"https://jhspedals.info/products/big-muff-2","instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":18},
{"id":20,"manufacturer":"JHS Pedals","model":"Emperor V2","effect_type":"Other","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":21900,"product_page":"https://jhspedals.info/products/emperor-v2","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":100},
{"id":11,"manufacturer":"JHS Pedals","model":"Flight Delay","effect_type":"Delay","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":24900,"product_page":"https://jhspedals.info/products/flight-delay","instruction_manual":"https://manuals.plus/jhs/pedals-flight-delay-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":57,"manufacturer":"JHS Pedals","model":"Germanium Boost","effect_type":"Utility","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":"https://jhspedals.info/products/germanium-boost","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":8,"manufacturer":"JHS Pedals","model":"Hard Drive","effect_type":"Gain","in_production":true,"width_mm":66.0,"depth_mm":121.9,"height_mm":40.6,"weight_grams":null,"msrp_cents":19900,"product_page":"https://jhspedals.info/products/hard-drive","instruction_manual":"https://manuals.plus/jhs/pedals-hard-drive-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":78},
{"id":25,"manufacturer":"JHS Pedals","model":"Haunting Mids","effect_type":"Utility","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":14900,"product_page":"https://jhspedals.info/products/haunting-mids","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":10,"manufacturer":"JHS Pedals","model":"Kilt 10","effect_type":"Gain","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":24900,"product_page":"https://jhspedals.info/products/kilt-10","instruction_manual":"https://manuals.plus/jhs/pedals-kilt-10-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":9,"manufacturer":"JHS Pedals","model":"Kilt V2","effect_type":"Gain","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":19900,"product_page":"https://jhspedals.info/products/kilt-v2","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":100},
{"id":22,"manufacturer":"JHS Pedals","model":"Kodiak","effect_type":"Other","in_production":true,"width_mm":66.0,"depth_mm":121.9,"height_mm":40.6,"weight_grams":null,"msrp_cents":21900,"product_page":"https://jhspedals.info/products/kodiak","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":10},
{"id":56,"manufacturer":"JHS Pedals","model":"Lizard Queen","effect_type":"Fuzz","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":"https://jhspedals.info/products/lizard-queen","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":28,"manufacturer":"JHS Pedals","model":"Milkman","effect_type":"Delay","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":17900,"product_page":"https://jhspedals.info/products/milkman","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":26,"manufacturer":"JHS Pedals","model":"Moonshine V2","effect_type":"Gain","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":19900,"product_page":"https://jhspedals.info/products/moonshine-v2","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":81},
{"id":1,"manufacturer":"JHS Pedals","model":"Morning Glory Clean","effect_type":"Gain","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":17900,"product_page":"https://jhspedals.info/products/morning-glory-clean","instruction_manual":"https://manuals.plus/jhs/pedals-morning-glory-clean-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":2,"manufacturer":"JHS Pedals","model":"Morning Glory V4","effect_type":"Gain","in_production":true,"width_mm":55.9,"depth_mm":121.9,"height_mm":40.6,"weight_grams":null,"msrp_cents":19900,"product_page":"https://jhspedals.info/products/morning-glory-v4","instruction_manual":"https://manuals.plus/jhs/pedals-morning-glory-v4-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":43},
{"id":15,"manufacturer":"JHS Pedals","model":"Muffuletta","effect_type":"Fuzz","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":24900,"product_page":"https://jhspedals.info/products/muffuletta","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":100},
{"id":5,"manufacturer":"JHS Pedals","model":"Notad\u00fcmbl\u00eb","effect_type":"Gain","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":11900,"product_page":"https://jhspedals.info/products/notadumble","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":4,"manufacturer":"JHS Pedals","model":"Notakl\u00f6n","effect_type":"Gain","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":11900,"product_page":"https://jhspedals.info/products/notaklon","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":"Standard, Pink, Splatter","data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":52,"manufacturer":"JHS Pedals","model":"Notakl\u00f6n Blackout","effect_type":"Gain","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":"https://jhspedals.info/products/notaklon-blackout","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":33,"manufacturer":"JHS Pedals","model":"Overdrive Preamp","effect_type":"Gain","in_production":false,"width_mm":119.4,"depth_mm":94.0,"height_mm":42.2,"weight_grams":null,"msrp_cents":17900,"product_page":"https://jhspedals.info/products/overdrive-preamp","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":51},
{"id":19,"manufacturer":"JHS Pedals","model":"PG-14","effect_type":"Gain","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":19900,"product_page":"https://jhspedals.info/products/pg-14","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":81},
{"id":13,"manufacturer":"JHS Pedals","model":"PackRat","effect_type":"Gain","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":24900,"product_page":"https://jhspedals.info/products/packrat","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":"Standard, White","data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":100},
{"id":62,"manufacturer":"JHS Pedals","model":"Panther Cub","effect_type":"Delay","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":"https://jhspedals.info/products/panther-cub","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":30,"manufacturer":"JHS Pedals","model":"Prestige","effect_type":"Utility","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":12900,"product_page":"https://jhspedals.info/products/prestige","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":16,"manufacturer":"JHS Pedals","model":"Pulp N Peel V4","effect_type":"Compression","in_production":true,"width_mm":66.0,"depth_mm":121.9,"height_mm":38.1,"weight_grams":null,"msrp_cents":22900,"product_page":"https://jhspedals.info/products/pulp-n-peel-v4","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":100},
{"id":65,"manufacturer":"JHS Pedals","model":"ROSS Chorus","effect_type":"Other","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":63,"manufacturer":"JHS Pedals","model":"ROSS Compressor","effect_type":"Compression","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":64,"manufacturer":"JHS Pedals","model":"ROSS Distortion","effect_type":"Gain","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":67,"manufacturer":"JHS Pedals","model":"ROSS Fuzz","effect_type":"Fuzz","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":66,"manufacturer":"JHS Pedals","model":"ROSS Phaser","effect_type":"Other","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":null,"instruction_manual":null,"image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":54,"manufacturer":"JHS Pedals","model":"Spring Tank","effect_type":"Reverb","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":"https://jhspedals.info/products/spring-tank","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":48,"manufacturer":"JHS Pedals","model":"Summing Amp","effect_type":"Utility","in_production":true,"width_mm":91.4,"depth_mm":38.1,"height_mm":25.4,"weight_grams":null,"msrp_cents":8500,"product_page":"https://jhspedals.info/products/summing-amp","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":19},
{"id":53,"manufacturer":"JHS Pedals","model":"SuperBolt V2","effect_type":"Gain","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":19900,"product_page":"https://jhspedals.info/products/superbolt-v2","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC or 18V DC","power_current_ma":100},
{"id":51,"manufacturer":"JHS Pedals","model":"Sweet Tea V3","effect_type":"Multi Effects","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":34500,"product_page":"https://jhspedals.info/products/sweet-tea-v3","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":49,"manufacturer":"JHS Pedals","model":"Switchback","effect_type":"Utility","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":12000,"product_page":"https://jhspedals.info/products/switchback","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":31},
{"id":60,"manufacturer":"JHS Pedals","model":"The Bulb","effect_type":"Gain","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":"https://jhspedals.info/products/the-bulb","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":12,"manufacturer":"JHS Pedals","model":"The Violet","effect_type":"Gain","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":19900,"product_page":"https://jhspedals.info/products/the-violet","instruction_manual":"https://manuals.plus/jhs/pedals-the-violet-manual","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":32,"manufacturer":"JHS Pedals","model":"Tidewater","effect_type":"Other","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":13500,"product_page":"https://jhspedals.info/products/tidewater","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":21,"manufacturer":"JHS Pedals","model":"Unicorn V2","effect_type":"Other","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":21900,"product_page":"https://jhspedals.info/products/unicorn-v2","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":100},
{"id":61,"manufacturer":"JHS Pedals","model":"VCR (Space Commander)","effect_type":"Multi Effects","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":"https://jhspedals.info/products/vcr-space-commander","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":80},
{"id":58,"manufacturer":"JHS Pedals","model":"Voice Tech","effect_type":"Utility","in_production":false,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":null,"product_page":"https://jhspedals.info/products/voice-tech","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"Medium","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":null},
{"id":31,"manufacturer":"JHS Pedals","model":"Whitey Tighty","effect_type":"Compression","in_production":true,"width_mm":null,"depth_mm":null,"height_mm":null,"weight_grams":null,"msrp_cents":13500,"product_page":"https://jhspedals.info/products/whitey-tighty","instruction_manual":"https://www.jhspedals.com/web/content/1254?unique=2d2386ed1fdc615577de819199151ad1ef84c033&download=true","image_path":null,"color_options":null,"data_reliability":"High","bypass_type":null,"signal_type":null,"circuit_type":null,"mono_stereo":"Mono","preset_count":0,"midi_capable":false,"has_tap_tempo":false,"battery_capable":false,"has_software_editor":false,"power_voltage":"9V DC","power_current_ma":100}];

const EFFECT_TYPES = ['All', ...Array.from(new Set(DATA.map(d => d.effect_type).filter((t): t is string => t !== null))).sort()];

const columns: ColumnDef<Pedal>[] = [
  { label: 'Manufacturer', width: 160, sortKey: 'manufacturer',
    render: p => <span style={{ color: '#f0f0f0', fontSize: '12.5px', fontWeight: 600, fontFamily: "'Helvetica Neue', sans-serif" }}>{p.manufacturer}</span> },
  { label: 'Model', width: 200, sortKey: 'model',
    render: p => <span style={{ color: '#d0d0d0' }}>{p.model}</span> },
  { label: 'Type', width: 120, align: 'center', sortKey: 'effect_type',
    render: p => p.effect_type
      ? <span className={`effect-badge effect-badge--${p.effect_type.toLowerCase().replace(/[\s/]+/g, '-')}`}>{p.effect_type}</span>
      : <span className="null-value">{'\u2014'}</span> },
  { label: 'Status', width: 80, align: 'center', sortKey: 'in_production',
    render: p => (
      <span className={`status-badge status-badge--${p.in_production ? 'in-production' : 'discontinued'}`}>
        {p.in_production ? 'Active' : 'Disc.'}
      </span>
    ) },
  { label: 'MSRP', width: 80, align: 'right', sortKey: 'msrp_cents',
    render: p => p.msrp_cents != null
      ? <>{formatMsrp(p.msrp_cents)}</>
      : <span className="null-value">{'\u2014'}</span> },
  { label: 'Dimensions', width: 160, align: 'center',
    render: p => p.width_mm != null && p.depth_mm != null && p.height_mm != null
      ? <>{formatDimensions(p.width_mm, p.depth_mm, p.height_mm)}</>
      : <span className="null-value">{'\u2014'}</span> },
  { label: 'Power', width: 100, align: 'center',
    render: p => p.power_voltage != null || p.power_current_ma != null
      ? <>{formatPower(p.power_voltage, p.power_current_ma)}</>
      : <span className="null-value">{'\u2014'}</span> },
  { label: 'Reliability', width: 80, align: 'center', sortKey: 'data_reliability',
    render: p => p.data_reliability
      ? <span className={`reliability-badge reliability-badge--${p.data_reliability.toLowerCase()}`}>{p.data_reliability}</span>
      : <span className="null-value">{'\u2014'}</span> },
];

const filters: FilterConfig<Pedal>[] = [
  { label: 'Type', options: EFFECT_TYPES,
    predicate: (p, v) => p.effect_type === v },
  { label: 'Status', options: ['All', 'In Production', 'Discontinued'],
    predicate: (p, v) => (v === 'In Production') === p.in_production },
  { label: 'Reliability', options: ['All', 'High', 'Medium', 'Low'],
    predicate: (p, v) => p.data_reliability === v },
];

const renderExpandedRow = (p: Pedal): ReactNode => (
  <>
    {p.bypass_type != null && (
      <div className="data-table__detail">
        <div className="data-table__detail-label">Bypass Type</div>
        <div className="data-table__detail-value">{p.bypass_type}</div>
      </div>
    )}
    {p.signal_type != null && (
      <div className="data-table__detail">
        <div className="data-table__detail-label">Signal Type</div>
        <div className="data-table__detail-value">{p.signal_type}</div>
      </div>
    )}
    {p.circuit_type != null && (
      <div className="data-table__detail">
        <div className="data-table__detail-label">Circuit Type</div>
        <div className="data-table__detail-value">{p.circuit_type}</div>
      </div>
    )}
    {p.mono_stereo != null && (
      <div className="data-table__detail">
        <div className="data-table__detail-label">Mono/Stereo</div>
        <div className="data-table__detail-value">{p.mono_stereo}</div>
      </div>
    )}
    <div className="data-table__detail">
      <div className="data-table__detail-label">MIDI Capable</div>
      <div className="data-table__detail-value">
        <span className={p.midi_capable ? 'bool-yes' : 'bool-no'}>{p.midi_capable ? 'Yes' : 'No'}</span>
      </div>
    </div>
    {p.preset_count > 0 && (
      <div className="data-table__detail">
        <div className="data-table__detail-label">Presets</div>
        <div className="data-table__detail-value data-table__detail-value--highlight">{p.preset_count}</div>
      </div>
    )}
    <div className="data-table__detail">
      <div className="data-table__detail-label">Tap Tempo</div>
      <div className="data-table__detail-value">
        <span className={p.has_tap_tempo ? 'bool-yes' : 'bool-no'}>{p.has_tap_tempo ? 'Yes' : 'No'}</span>
      </div>
    </div>
    <div className="data-table__detail">
      <div className="data-table__detail-label">Battery</div>
      <div className="data-table__detail-value">
        <span className={p.battery_capable ? 'bool-yes' : 'bool-no'}>{p.battery_capable ? 'Yes' : 'No'}</span>
      </div>
    </div>
    <div className="data-table__detail">
      <div className="data-table__detail-label">Software Editor</div>
      <div className="data-table__detail-value">
        <span className={p.has_software_editor ? 'bool-yes' : 'bool-no'}>{p.has_software_editor ? 'Yes' : 'No'}</span>
      </div>
    </div>
    {p.color_options != null && (
      <div className="data-table__detail">
        <div className="data-table__detail-label">Color Options</div>
        <div className="data-table__detail-value">{p.color_options}</div>
      </div>
    )}
    {p.product_page != null && (
      <div className="data-table__detail">
        <div className="data-table__detail-label">Product Page</div>
        <div className="data-table__detail-value">
          <a href={p.product_page} target="_blank" rel="noopener noreferrer" onClick={e => e.stopPropagation()} className="detail-link">
            {p.product_page}
          </a>
        </div>
      </div>
    )}
    {p.instruction_manual != null && (
      <div className="data-table__detail">
        <div className="data-table__detail-label">Instruction Manual</div>
        <div className="data-table__detail-value">
          <a href={p.instruction_manual} target="_blank" rel="noopener noreferrer" onClick={e => e.stopPropagation()} className="detail-link">
            {p.instruction_manual}
          </a>
        </div>
      </div>
    )}
  </>
);

const stats = (data: Pedal[]) => {
  const inProd = data.filter(p => p.in_production).length;
  const types = new Set(data.map(p => p.effect_type).filter(t => t !== null)).size;
  return `${data.length} pedals \u00b7 ${inProd} in production \u00b7 ${types} effect types`;
};

const Pedals = () => (
  <DataTable<Pedal>
    title="Pedal Database"
    entityName="pedal"
    entityNamePlural="pedals"
    stats={stats}
    data={DATA}
    columns={columns}
    filters={filters}
    searchFields={['manufacturer', 'model']}
    searchPlaceholder="Search pedals..."
    renderExpandedRow={renderExpandedRow}
    defaultSortKey="manufacturer"
  />
);

export default Pedals;
